### PR TITLE
Remove ECK (and Flag) references

### LINKED ISSUE #67: Remove legacy ECK methods / files
Looks like theres at least a template hanging about `eck-entity--alert-banner.html.twig`
I think also there is a custom access handler in /src/access which isn't used that can be removed.
Do a pass over the .module files and services to make sure their no longer referencing flag or ECK

### PR DESCRIPTION
**Pull request by andybroomfield**
Close #67

Remove ECK template
Remove References to ECK in comments
Remove Flag settings in localgov_alert_banner entity on config
Remove custom access service for viewing the ECK entity page

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Changes look okay.  I tested in a fresh Drupal install and all worked fine.  Noticed a minor issue that the module info file doesn't declare field_group as a dependency.

**Comment by andybroomfield** [comment]
@Adnan-cds I don't think we actully use field group as a dependancy as we code up our own groups in the form, though thats a new issue to remove it.

**Comment by andybroomfield** [comment]
@Adnan-cds Field group issues is #84.

**Comment by Adnan-cds** [comment]
Hi Andy,
Sorry, the module info file [does mention field group as a dependency](https://github.com/localgovdrupal/localgov_alert_banner/blob/51a8a1bdd4ef22d56aff4dbacc962a2944850c60/localgov_alert_banner.info.yml#L9).  But it mentions it as **drupal:field_group** instead of **field_group:field_group** which confused me :(

#84 is relevant of couse.

FAO @andybroomfield

**Comment by andybroomfield** [comment]
Assume can be approved to move this forward as field group filled as new issue?

**Comment by Adnan-cds** [comment]
Hi Andy,
I am happy for this change to be approved.  I am not a reviewer of this pull request.  So please let me know if it would be okay for me to approve this.

**Comment by andybroomfield** [comment]
@Adnan-cds Have added you as a reviewer.

**Review by Adnan-cds — APPROVED** [review]
I am happy with this change given that #84 dealing with the field_group dependency :)

**Pull request merged**
