### PR TITLE
Release v.1.1.1

### PR DESCRIPTION
**Pull request by andybroomfield**
Bug fix release to address cache issue in #150 (PR #152)

Commits on Jun 29, 2021
@Adnan-cds
Fix for typo in cache context name …
8f0621c
Commits on Jun 30, 2021
@andybroomfield
Merge pull request #149 from localgovdrupal/fix/typo-in-cache-context… …
6b5d7a6
@andybroomfield
Move the cacheContexts and cacheTags to the alert banner entity …
0780491
Commits on Jul 01, 2021
@andybroomfield
Initial alterations to add cache contexts and tags
04a5747
Commits on Jul 02, 2021
@andybroomfield
Remove $this->addCacheContexts($contexts) as returning by merging wit… …
06ab96b
Commits on Jul 05, 2021
@andybroomfield
Merge pull request #152 from localgovdrupal/fix/150-cache-tags …
3e40ca8

### CODE REVIEW

**Comment by Adnan-cds** [comment]
I can confirm that this fix is working as expected in one of our dev sites.  However many faceted searches I do, the number of cache entries for the Alert banner block remains fixed in the cache_render database table.  When I edited an existing alert banner, it appeared instantly to anonymous users.

**Comment by andybroomfield** [comment]
@Adnan-cds see #155 for the cache url path fix, or is this a new issue?

**Review by stephen-cox — APPROVED** [review]
Happy to get this released. We can always get another release out if there are further cache issues.

**Comment by stephen-cox** [comment]
@andybroomfield @ekes @finnlewis Just thinking about what changelog messages look like and contain. Each of us does it differently. Does that matter or should we standardise release messages and changelogs?

**Comment by andybroomfield** [comment]
@stephen-cox I'm just copying the commit logs, I think we should be able to put a template together in the .githhub repo.

**Pull request merged**
