### PR TITLE
Follow up performance improvements

### PR DESCRIPTION
**Pull request by andybroomfield**
Remove protected array for current banners and move the cache contexts
into th build method. Also amend the kernal test to account for #cache
inside the render array.

### CODE REVIEW

**Comment by andybroomfield** [comment]
@rupertj have managed to remove the need for storing current alert banners as a class property. Turns out it's not stored anyway between the build and getCacheContexts methods, so just applied it to the build render array.

**Comment by rupertj** [comment]
Looks good, although it'd be better to use CacheableMetadata, as that'd add all the relevant metadata from the node, not just contexts. (I'm thinking cache tags should come across too).

**Comment by andybroomfield** [comment]
@rupertj Yeah, I was looking at that, though we already have a getCacheTags and I think they should bubble. I can look at those in part 3 along with the manager service.

**Review by rupertj — APPROVED** [review]

**Comment by rupertj** [comment]
I've just realised we're talking about a custom entity, and I don't think it implements the interface required to use CacheableMetadata right now, so doing it like this MR does is best for now anyway.

**Pull request merged**
