### PR TITLE
"Remove hide link" checkbox for full page banner

### LINKED ISSUE #189: [Bug] Selecting "Remove hide link" breaks the full page banner
Selecting the **Remove hide link** checkbox on a Full page banner edit form stops Content editors from publishing the banner.

We don't really need the *Remove hide link* checkbox on Full page banners as hiding this link from the full page banner means people will get stuck seeing the banner and will have no way to close the banner and reach the site.

Tasks:
- [x] Remove the "Remove hide link" checkbox from [form display for Full page banners](https://github.com/localgovdrupal/localgov_alert_banner/blob/b9b6f962daf827a65868b1b21383c4b4957c99f1/modules/localgov_alert_banner_full_page/config/install/core.entity_form_display.localgov_alert_banner.localgov_full_page.default.yml#L49).
- [x] Add an update hook to remove the *Remove hide link* checkbox from existing form display config for Full page banners.

### PR DESCRIPTION
**Pull request by Adnan-cds**
Resolves #189

Updated config file and accompanying programmatic update to hide the "Remove hide link" checkbox from the Full page alert banner's edit form.

The "Remove hide link" checkbox is irrelevant for Full page alert banners as we don't want to remove the "Hide" link from full page banners.  This is because a full page banner without a hide link prevents people from reaching the actual site content!

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Leaving it in Draft state for now.  Waiting for test runs to be back to normal.

**Comment by Adnan-cds** [comment]
Tests are passing, so ready for review :)

**Review by andybroomfield — APPROVED** [review]
This makes sense and I've been able to verify the hide link is removed following db update.
I noticed that pre update, it wasn't possible to display the banner anyway if the hide link was checked, was that intentional. Either way better it is removed for the full page version.

**Comment by Adnan-cds** [comment]
> I noticed that pre update, it wasn't possible to display the banner anyway if the hide link was checked, was that intentional

Hi Andy, thanks for the approval.  But no, this was not [intentional](https://github.com/localgovdrupal/localgov_alert_banner/issues/189).

**Pull request merged**
