### PR TITLE
1.1.2 Release

### PR DESCRIPTION
**Pull request by andybroomfield**
Should be last bugfix release before schduled alert banners in 1.2.

Commits on Jul 02, 2021
@andybroomfield
Fix adding cache contexts only when it has an effect on visibility …
ab0a712
Commits on Jul 05, 2021
@markconroy
swap modifier to element to follow BEM
77f3a83
Commits on Jul 07, 2021
@andybroomfield
Fix display the banner link when no title …
5c46105
Commits on Jul 08, 2021
@Adnan-cds
Cache clear can now rely on cache tag invalidation. …
430d0e6
@markconroy
Merge pull request #157 from localgovdrupal/hotfix/1.x-bem-coding-sta… …
1d7638c
@markconroy
Merge pull request #148 from localgovdrupal/fix/147-link-no-title …
a0f2c7d
Commits on Jul 16, 2021
@Adnan-cds
Revert "Cache clear can now rely on cache tag invalidation." …
d5a57ca
@Adnan-cds
Cache clear improvement. …
ec37303
@andybroomfield
Merge pull request #155 from localgovdrupal/fix/154-cache-context-con… …
c1ce09c
Commits on Jul 26, 2021
@andybroomfield
Merge pull request #158 from localgovdrupal/feature/no-flush-all-cache …

### CODE REVIEW

**Comment by stephen-cox** [comment]
Tests are failing because they are building the 2.0.0 version of LocalGov Drupal not the latest release which is 2.1.2. I think this is an issue with the GitHub Actions file, but will need to investigate

**Comment by stephen-cox** [comment]
Maybe we want to rethink how the tests are run for this module. See: https://github.com/localgovdrupal/localgov_alert_banner/pull/159#issuecomment-889261999

**Comment by andybroomfield** [comment]
If the test fails relates to the new workflow stuff that isn't used in 1.1.2, could we merge this with the fail? 
This release has some important cache fixes that would be really usefull to get released ASAP.

/cc @stephen-cox @Adnan-cds @danchamp

**Review by stephen-cox — APPROVED** [review]
@andybroomfield Been trying to get to the bottom of why the tests are failing on this. I haven't fully worked it out, but it's not to do with this the changes here, so happy to approve even though the tests fail

**Pull request merged**
