### PR TITLE
1.8.1 release

### PR DESCRIPTION
**Pull request by andybroomfield**
First bugfix of the 1.8 series!
- Check if emergency publisher role exists before changing permissions #389

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Great work people!

**Comment by finnlewis** [comment]
This is an edge case, and sorry that it was @AWearring at the edge! But a good catch for others I reckon :)

**Comment by AWearring** [comment]
Morning @finnlewis
Are you able to merge this so it becomes the latest release, please?

**Comment by andybroomfield** [comment]
@AWearring I'll do that for you now.

**Pull request merged**
