### PR TITLE
1.5.2 release

### PR DESCRIPTION
**Pull request by andybroomfield**

### CODE REVIEW

**Comment by andybroomfield** [comment]
The test fail is becuase javascript tests are broken, however this release is just a css change.

**Comment by andybroomfield** [comment]
Checked visually.

Screenshot 2022-11-07 at 2 40 53 pm

And Bartick
Screenshot 2022-11-07 at 2 41 36 pm

**Comment by andybroomfield** [comment]
Added Olivero compatability.

**Review by finnlewis — APPROVED** [review]
:)

**Comment by finnlewis** [comment]
We know the tests are failing, but that is unrelated.

**Pull request merged**
