### PR TITLE
Remove 1 banner limitation and add the unpublish others as an option

### LINKED ISSUE #99: Remove the one banner live limitation, replace with an option to unpublish others on the confirmation page
Follow up to #98.

Instead of forcing only one banner at a time to be published, auto unpublishing any other banner. It should be up to content designers to decide how many banners should be published. The agreed solution is to on the confirmation page for putting a banner live, to have a check box option (pre ticked) to unpublish the other banners (of the same bundle).

- [x] Add a check box to the comfirmation page to unpublish others (default checked?).
- [x] Move the current unpublish others in the entity save to the confirmation form submit
- [x] Update confirmation form test to check unpublish others checkbox
- [x] Update the display block to support multiple banners
- [x] Move the hide token from state to the entity itself (as now different hide states so will hide all)
- [x] Determine the order to display the banners
- [x] Write test for this behaviour
- [x] Update existing tests.

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #99.

This removes the single alert banner limitation, and replaces it with a checkbox on the alert banner confirmation page to unpublish others.
This also updates the banner order to go by (if the type_of_alert) field is present, by Death of notable person, major, minor, annoucement. Then by date updated.
Move the dismiss token from state api and onto the entity (**Note this will require running database updates to update the entity**).
Updates the tests to account for new banner behaviour.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Drafiting this as a PR so people can check work to date.

**Comment by andybroomfield** [comment]
This should be mostly done now, but need to get the test working before merging.

**Comment by andybroomfield** [comment]
This is ready for review now.
I've made the banner order test use a kernel test, hopefully it isn't too complicated to follow what it is testing, but if it is let up know.

**Comment by finnlewis** [comment]
Thanks @andybroomfield  - just testing now.

**Comment by finnlewis** [comment]
I've tested this locally on a fresh install of LocalGov Drupal and on the Lambeth site, both appear to work as expected. I can set multiple banners to be live at the same time, and unselect the box to unpublish other banners. 

Works for me. 

@ekes want to take a look at the code?

**Review by finnlewis — APPROVED** [review]
Looks good to me! 

Tested locally on fresh install of LocalGov Drupal and on a copy of the Lambeth site. 

I've taken a cursory look at the code and can't see anything that jumps out. 

Tests and functionality work for me so happy to approve. 

Thanks @andybroomfield !

**Comment by finnlewis** [comment]
It would be great to get this one merged. Are you waiting on more reviewing @andybroomfield ? 
I've just pinged @ekes to see if he has anything to add.

**Comment by andybroomfield** [comment]
@finnlewis if your happy I will merge this tomorrow and prep a release.

**Pull request merged**
