### PR TITLE
Update blocks to use the new LocalGov Base theme

### PR DESCRIPTION
**Pull request by stephen-cox**
Part of localgovdrupal/localgov#288 and localgovdrupal/localgov#317

### CODE REVIEW

**Comment by stephen-cox** [comment]
Tests are failing because this PR needs to be merged first: localgovdrupal/localgov#322 as well as the fixes to the tests in #159

**Comment by andybroomfield** [comment]
@stephen-cox what parts of #159 are required to get the tests to pass?

**Comment by stephen-cox** [comment]
I've extracted out the test fixes to #167.

**Review by finnlewis — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
