### PR TITLE
1.8.x Refactor

### PR DESCRIPTION
**Pull request by andybroomfield**
Current blockers

- [x] Move the visible check to alert banner manager #355

Propose we handle in patch release as needs more discussion

- Adds banner type as ARIA label to banner article elements #346
- Show type of alert in the alert banner #376
- Provide a hook or event subscriber for modifying the current alert banners #262

Don't know 
- Fatal database error trying to enable group_alert_banner #315

### CODE REVIEW

**Comment by andybroomfield** [comment]
Suggest re rename this branch becuase having a 1.8.x branch seems to be the root of the test failures.
See https://github.com/localgovdrupal/localgov_shared_workflows/issues/3

**Comment by andybroomfield** [comment]
and yet renaming this branch causes this one to pass?

**Comment by andybroomfield** [comment]
List of PRs that make up the refactor.
- fix: additional strict type fixes #332
- Initial refactor of revision provider and access #333
- Remove unused add type template #335
- Move getCurrentBanners to a service #337
- Run tests on 1.8.x branch #339
- Remove default_argument_skip_url from group manage alert banners view #336
- Tests fix #340
- Opt into the Gin content form routes (edit theme) #341
- Fix alert banner entity type paths and local tasks #343
- Fix routes to localgov_alert_banner_types in permissions test #344
- Remove js-cookie dependancy #347
- Feature: Replace js cookie #356
- Mark support for Drupal 11 and drop Drupal 9 #351
- fix/1.x 363 emergency publisher perms #364
- [1.8.x] fix: add ignore next line #366
- Fix todos in admin view functional test #370
- Update readme with instructions on disabling CSS #375
- Move the visible check to alert banner manager #355
- Feature/378/remove polyfills #381

**Comment by andybroomfield** [comment]
## What does this change?

Refactors the Alert banner entity, alert banner block and adds an alert banner manager service.
Adds Drupal 11 support and drops Drupal 9 support.



## How to test

- Check no more Drupal 11 deprecations
- Check installable on Drupal 11.
- Check alert banners can be created, viewed, dismissed.



## How can we measure success?

Alert banner should function as before, now with Drupal 11 support and the deperacation warnings should be gone.
This release does not contan functional changes.



## Have we considered potential risks?

Check that refactor does not have any side effects.



## Images

n/a


## Accessibility

n/a (follow up PRs to be added in 1.8.1)

**Comment by finnlewis** [comment]
@andybroomfield I've tested this on Drupal 10  / localgov 3.x and all functionality seems to work as smoothly as ever. 

Now trying to test on Drupal 11, although we're not explicitly testing again Drupal 11 yet and I imagine it will be a while until many people are using Drupal 11.

**Comment by finnlewis** [comment]
How are you installing localgov Drupal 11 @andybroomfield ?

I'm trying this : 

```
composer create-project localgovdrupal/localgov-project:^4.x-dev MY_PROJECT --no-install
```

But then getting composer issues. 

```
    - localgovdrupal/localgov[3.0.0-alpha1, ..., 3.x-dev] require drupal/core ^10.0 -> satisfiable by drupal/core[10.0.0-alpha1, ..., 10.4.x-dev].
    
```

**Comment by millnut** [comment]
Hey @finnlewis yeah profile blocks the install currently from that branch as it's very experimental. I've been installing the 3.x branch and upgrading to D11 and testing

**Comment by finnlewis** [comment]
> Hey @finnlewis yeah profile blocks the install currently from that branch as it's very experimental. I've been installing the 3.x branch and upgrading to D11 and testing

Thanks @millnut  - can you point me in the right direction with some quick steps to upgrade to D11?

**Comment by finnlewis** [comment]
Meanwhile, @andybroomfield , tested on a vanilla Drupal 11 install, and it installs and functions well.

The only thing I notice is that 

1. I need to place the block manually in a region.
2. Placing it in the header region does not render a full width banner, it gets bunched up next to the branding. 

image


I guess for now we are targeting people who are installing this as part of LocalGov Drupal, so perhaps that's something for the future?

**Comment by andybroomfield** [comment]
@finnlewis Yes, I've been thinking of providing an olivero block, and then the localgov theme blocks could use the method @rupertj is / has created.
I use the hero region on Olivero.

**Comment by andybroomfield** [comment]
Just a note, I've added @markconroy PR on removing polyfills to this PR also. Apolgies if that means you need to restart testing.

**Review by markconroy — APPROVED** [review]
- Tested on existing install, all fine.
- Tested on clean install of LGD, all fine.

**Pull request merged**
