### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by Adnan-cds**
Changelog:
#159 Scheduled alert banners.
#170 Send string in both instances of revision link for table.
#172 Add routing for accessing revision paths.
#133 Full page alert banner.

We have new features.  So bumping up the minor version number.

### CODE REVIEW

**Review by stephen-cox — APPROVED** [review]
This has been been previously reviewed, so happy to approve a 1.2.0 release.

As there are a couple of new features we should briefly highlight these in the release notes and announce the release in Slack so it can be included in the next news letter.

**Comment by andybroomfield** [comment]
Screenshot 2021-09-16 at 11 41 45 am
Seems to all work.

**Review by andybroomfield — APPROVED** [review]
Release Notes :
Alters Alert Banner to use Workflow and Content Moderation
Adds support for Scheduling Alert Banners if the Scheduled Transitions module is installed
Adds New submodule with a full screen alert banner type.

**Comment by Adnan-cds** [comment]
Thanks Andy, thanks Steve.  I will create a release tag using the release notes added by Andy above.

**Pull request merged**
