### PR TITLE
Make alert banner admin view the default collection page

### LINKED ISSUE #65: Update paths for Add / Edit operations
> I notices the path includes .../entity-type/bundle/id (bundle not being necessary and actually being a bit confusing on breadcrumb to path); 
> but more important shouldn't the path of the view list be the same as the one created for the collection-list to override it? Or is there a plan to put it somewhere/change the collection-list path?

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #65

When saving an alert banner, the confirmation form will redirect to the collection. The user should redirect to the admin view. This fixes the issue by making the entity collection have the same path as the admin view.

Includes basic test, however could be revised as a kernal test in the future.

### CODE REVIEW

**Comment by ekes** [comment]
Makes sense to me.

Although still wants the follow-up for all the other URLs to make them the same pattern.

**Comment by andybroomfield** [comment]
@ekes I checked and all urls hang of /admin/content/alert-banner/
is this correct, originally it was alert-banners but I saw you changed the view to the non plural.

````
 *   links = {
 *     "canonical" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}",
 *     "add-page" = "/admin/content/alert-banner/localgov_alert_banner/add",
 *     "add-form" = "/admin/content/alert-banner/localgov_alert_banner/add/{localgov_alert_banner_type}",
 *     "edit-form" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/edit",
 *     "delete-form" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/delete",
 *     "status-form" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/status",
 *     "version-history" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/revisions",
 *     "revision" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/revisions/{localgov_alert_banner_revision}/view",
 *     "revision_revert" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/revisions/{localgov_alert_banner_revision}/revert",
 *     "revision_delete" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/revisions/{localgov_alert_banner_revision}/delete",
 *     "translation_revert" = "/admin/content/alert-banner/localgov_alert_banner/{localgov_alert_banner}/revisions/{localgov_alert_banner_revision}/revert/{langcode}",
 *     "collection" = "/admin/content/alert-banner",
 *   },
````

**Comment by andybroomfield** [comment]
@ekes remove `/localgov_alert_banner/` from the url pattern?

**Comment by ekes** [comment]
Yes the `/localgov_alert_banner/` seems over confusing. 

The plural ... erm might have been my mistake. I can't remember. Module names are plural. Entity names are singular. So no that makes sense singular.

This is all I had for geo:
```
 *     "add-form" = "/admin/content/geo/add/{localgov_geo_type}",
 *     "add-page" = "/admin/content/geo/add",        
 *     "canonical" = "/admin/content/geo/{localgov_geo}",
 *     "edit-form" = "/admin/content/geo/{localgov_geo}/edit",
 *     "delete-form" = "/admin/content/geo/{localgov_geo}/delete",
 *     "collection" = "/admin/content/geo"
```
Obviously it doesn't have the revisions additions.

**Comment by ekes** [comment]
Guess we should really be content/localgov/* for stuff that's ours. But that hurts my head at this moment. If we're consistent then can review if we need to avoid path clashes later.

**Comment by ekes** [comment]
:+1:

**Comment by andybroomfield** [comment]
Ok to merge this @ekes now all tests pass?

**Pull request merged**
