### PR TITLE
Merge to release branch and create new release tag for 1.0.0-alpha3

### PR DESCRIPTION
**Pull request by finnlewis**
This is a pull request to review recent commits before tagging 1.0.0-alpha3

Each commit will already have been reviewed in a pull request, so this should be just a sanity check.

Comments welcome, or just a "looks good to me"!

### CODE REVIEW

**Review by Adnan-cds — APPROVED** [review]
looks good to me"! :D

**Comment by andybroomfield** [comment]
Did we resolve #89?

**Comment by finnlewis** [comment]
Just cross posting with #89 

@ekes and I were discussing this today, we think it will be fine.

We've removed the 1.0.1-alpha1 tag from Packagist and Github, which should result in no changes as it was the same as 1.0.0-alpha1.

So now we should be good to continue the increments

1.0.0-alpha1
1.0.0-alpha2
1.0.0-alpha3

up to (if needed)

1.0.0-beta1
1.0.0-beta2
...

Then 

1.0.0

**Comment by ekes** [comment]
There is already an 1.0.0-alpha2 but it was not getting pulled as 1.0.1-alpha1 was higher. 
Deleting 1.0.1-alpha1 at packagist (manually) has made 1.0.0-alpha2 the current version.

**Review by andybroomfield — APPROVED** [review]
Happy for this release to go ahead with new tags.

**Pull request merged**
