### PR TITLE
Update View for compatibility with other types

### PR DESCRIPTION
**Pull request by tanc**
Has the following changes:

1. Adds a 'Banner type' column showing the bundle.
2. Removes 'created' column.
3. Removes the filter restriction on bundle.
4. Changes date to slightly shorter format (same as core content view).
5. Adds sortable columns and responsive collapsing.
6. Adds 'Banner type' exposed filter.

### CODE REVIEW

**Comment by tanc** [comment]
Closes #95

**Comment by tanc** [comment]
image
Wide screen

**Comment by tanc** [comment]
image
Narrow screen demonstrating collapsed/hidden columns

**Comment by andybroomfield** [comment]
Thanks @tanc this looks good.
I'll kick off the discussion on config update, however this should be simple enough to pass around the config change and just merge this? @finnlewis

**Review by andybroomfield — APPROVED** [review]
Tested and these changes work, thanks @tanc 

I'm happy to merge this now, and pick up the config update in a new PR if we think that is needed.

**Pull request merged**
