### PR TITLE
Officially support Drupal 10

### PR DESCRIPTION
**Pull request by andybroomfield**
Mark module as supporting Drupal 10, now that condition field also 
supports Drupal 10 and field group is no longer a dependancy.

### CODE REVIEW

**Comment by finnlewis** [comment]
@Adnan-cds we're hoping you could take a look at this with respect to the full page sub-module.

**Comment by Adnan-cds** [comment]
Looks okay to me.  The [localgov_alert_banner_full_page submodule explicitly says](https://github.com/localgovdrupal/localgov_alert_banner/blob/1.x/modules/localgov_alert_banner_full_page/localgov_alert_banner_full_page.info.yml) that it is compatible with Drupal 8 and 9 only.  So there shouldn't be any confusion once the main module starts supporting Drupal 10.

**Comment by andybroomfield** [comment]
@Adnan-cds Just to confirm you would be ok for me to make a release announcing support for Drupal 10 without updating the sub module?
Do we know what needs to be updated before releasing? Do we need the field group dependency?

**Comment by Adnan-cds** [comment]
> Do we need the field group dependency?

Hi Andy, I just tested the submodule in a fresh site without the field_group module and it works fine.  So if you can please [remove the dependency on the field_group module](https://github.com/localgovdrupal/localgov_alert_banner/blob/9ee9c9bd2c872ca804f50e910c0d68e244ed4810/modules/localgov_alert_banner_full_page/localgov_alert_banner_full_page.info.yml#L9), that would be great :)

**Comment by finnlewis** [comment]
Discussing in Merge Monday, @andybroomfield will remove the dependency on drupal:field_group and mark as supported for Drupal 10.

**Review by Adnan-cds — APPROVED** [review]
Looks good to me.  Thanks :)

**Pull request merged**
