### PR TITLE
Fix for typo in the label for announcement type

### PR DESCRIPTION
**Pull request by Adnan-cds**
A not so significant change :)

Spotted it while setting up the Croydon site.

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Hi Andy,
I realized this is a config change will need an accompanying update hook implementation.  Let's leave it to rest now.  I will try to added an update hook in a week or so.

**Review by finnlewis — APPROVED** [review]
I think this is fine @Adnan-cds 

This might be a config change, but it would not break anything if it was or wasn't implemented on a site - there is not likely to be any dependency chain on this label, right?

**Comment by Adnan-cds** [comment]
> there is not likely to be any dependency chain on this label, right?

Nah, there shouldn't be any dependency.  It's just that the existing sites will continue to display the typo.

**Comment by andybroomfield** [comment]
This is fine, since we have to assume that a site might change these labels (we can communicate the change to the group for those that havn't caught the misspelling).

**Comment by Adnan-cds** [comment]
Great.  I am merging it then.

I won't raise any follow-up pull request for a new **release**.  A fixed typo in a label probably doesn't merit a new release.

**Pull request merged**
